In [1]:
import numpy as np
import pandas as pd
from os import path
from PIL import Image
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
import matplotlib.pyplot as plt
from collections import Counter
import spacy
import gensim
nlp = spacy.load('en_core_web_lg')

In [2]:
# Importing libraries 
import nltk 
import re 
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer 
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
import numpy as np
import pandas as pd
from keras.utils.np_utils import to_categorical

In [3]:
des = np.load('df_country.npy', allow_pickle=True)
des = pd.DataFrame(des)
des.columns = ['desc','country']

In [10]:
from keras.layers.recurrent import LSTM
from keras.layers.embeddings import Embedding
from keras.models import Model, Sequential
from keras.layers import Dense, Activation
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,classification_report
from sklearn.neural_network import MLPClassifier
from keras.wrappers.scikit_learn import KerasClassifier

from keras.layers import Input, Conv2D,Convolution1D, BatchNormalization, MaxPooling2D,MaxPool1D, Flatten, Dense, Dropout
from keras.optimizers import Adam
from keras.losses import binary_crossentropy as BC


In [32]:
### sample description
from sklearn.feature_extraction import text 

## remove stop words
stopwords = ["wine","rich","character",'pinor','noir',"flavor", "riesling","flavors","Cabernet Sauvignon","palate","aroma","hints","finish",'nose','note','ripe','Cabernet','cabernet','malbec',"Sauvignon",'mouth','year']
stop_words = text.ENGLISH_STOP_WORDS.union(stopwords)


## MLP

In [29]:

X = des['desc']
y = des['country']


X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.1,train_size=0.4, random_state=2)

print(X.size, X_train.size,X_test.size)

124584 49833 12459


In [33]:
from sklearn.neural_network import MLPClassifier

pipe=Pipeline([("vectorize",CountVectorizer(stop_words=stop_words)),("MLP",MLPClassifier(hidden_layer_sizes=(300,300,300),max_iter=8))])
pipe.fit(X_train,y_train)

res=pipe.predict(X_test)
print(confusion_matrix(y_test,res))
print(classification_report(y_test,res))

/home/mecon/.local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py:388: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['sauvignon'] not in stop_words.
  warnings.warn('Your stop_words may be inconsistent with '
/home/mecon/.local/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (8) reached and the optimization hasn't converged yet.
  warnings.warn(


[[ 170    1    0   87    1    0    4    0   95   27]
 [   0  131    2    5   22    1    4    0    1   85]
 [   0    0  219    0   76    2    5   16    2   25]
 [  90    0    1  262    4    0    1    0   76   29]
 [   1   11   42    3 1795    2   15  246    4  108]
 [   0    4    3    0    5  114    1    0    1  104]
 [   3    3    0    3   19    0 1790    3    2   91]
 [   0    0    3    0  169    0    2  390    0   15]
 [  89    0    0   89   14    0    4    0  423   42]
 [   6   16    6   16   52   26   29    8   25 5218]]
              precision    recall  f1-score   support

   Argentina       0.47      0.44      0.46       385
   Australia       0.79      0.52      0.63       251
     Austria       0.79      0.63      0.71       345
       Chile       0.56      0.57      0.56       463
      France       0.83      0.81      0.82      2227
     Germany       0.79      0.49      0.60       232
       Italy       0.96      0.94      0.95      1914
    Portugal       0.59      0.67   

In [59]:

X = des['desc']
y = des['country']


X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.05,train_size=0.2, random_state=2)

print(X.size, X_train.size,X_test.size)

124584 24916 6230


In [28]:
from sklearn.neural_network import MLPClassifier

pipe=Pipeline([("vectorize",CountVectorizer()),("MLP",MLPClassifier(hidden_layer_sizes=(300,300,300),max_iter=8))])
pipe.fit(X_train,y_train)

res=pipe.predict(X_test)
print(confusion_matrix(y_test,res))
print(classification_report(y_test,res))

/home/mecon/.local/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (8) reached and the optimization hasn't converged yet.
  warnings.warn(


[[  80    1    0   49    1    0    2    0   34   13]
 [   0   61    2    1   12    1    2    0    0   37]
 [   0    0   92    0   55    0    4    3    0   11]
 [  28    0    0  107    5    0    2    0   47   22]
 [   1    3   23    0  963    0    6   66    1   57]
 [   0    3    0    0    4   70    1    0    1   37]
 [   2    2    2    0    8    0  927    0    1   42]
 [   0    1    6    1  107    0    2  194    0    4]
 [  50    0    0   42    6    0    4    0  220   10]
 [   1    9    5    7   42   16   22    4    5 2580]]
              precision    recall  f1-score   support

   Argentina       0.49      0.44      0.47       180
   Australia       0.76      0.53      0.62       116
     Austria       0.71      0.56      0.62       165
       Chile       0.52      0.51      0.51       211
      France       0.80      0.86      0.83      1120
     Germany       0.80      0.60      0.69       116
       Italy       0.95      0.94      0.95       984
    Portugal       0.73      0.62   

In [40]:
vectorizer = CountVectorizer(stop_words=stop_words)
vector_mat = vectorizer.fit_transform(des['desc'])
vector_mat.shape

(124584, 23044)

## CNN

In [18]:

X = des['desc']
y = des['country']


X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2,train_size=0.2, random_state=2)

print(X.size, X_train.shape,X_test.shape)

124584 (24916,) (24917,)


In [12]:
num_labels=10

def cnn_model():
    model=Sequential()
    model.add(Embedding( len(X_train)+1, 300, input_length=20))
    model.add(Convolution1D(256, 3, padding='same'))
    model.add(MaxPool1D(3,3,padding='same'))
    model.add(Convolution1D(128, 3, padding='same'))
    model.add(MaxPool1D(3,3,padding='same'))
    model.add(Convolution1D(64, 3, padding='same'))
    model.add(Flatten())
    model.add(Dropout(0.1))
    model.add(BatchNormalization()) # (批)规范化层
    model.add(Dense(256,activation='relu'))
    model.add(Dropout(0.1))
    model.add(Dense(num_labels,activation='softmax'))

    model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
    return(model)
#model.fit(X_train_padded_seqs, y_train, batch_size=32, epochs=15,validation_data=(X_test_padded_seqs, y_test))

## RNN

In [13]:
pipe=Pipeline([('vectorizer', CountVectorizer()),("cnn",KerasClassifier(build_fn=cnn_model,nb_epoch=10,batch_size=128))])

pipe.fit(X_train,y_train)

res=pipe.predict(X_test)
print(confusion_matrix(y_test,res))
print(classification_report(y_test,res))



InvalidArgumentError: indices[1] = [0,9935] is out of order. Many sparse ops require sorted indices.
    Use `tf.sparse.reorder` to create a correctly ordered copy.

 [Op:SerializeManySparse]